services:
  api:
    build: .
    ports: ["8000:8000"]
    env_file: [./.env]
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    volumes: [.:/app]
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: pgvector/pgvector:pg16
    ports: ["5432:5432"]
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ai_research_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # THIS IS THE FIX: Mount the init script
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d ai_research_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: "redis:alpine"
    ports: ["6379:6379"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: